update dev branch

diff --git a/tasks/create_pks_admin_ldap_group_maps.yml b/tasks/create_pks_admin_ldap_group_maps.yml
--- a/tasks/create_pks_admin_ldap_group_maps.yml
+++ b/tasks/create_pks_admin_ldap_group_maps.yml
@@ -9,23 +9,33 @@ platform: linux
 
 
 inputs:
+- name: config # contains the base configuration file
 - name: env # contains the env file with target OpsMan Information
-- name: vars # variable files to be made available
-  optional: true
 - name: secrets
   # secret files to be made available
   # separate from vars, so they can be store securely
   optional: true
 
 params:
-  PAS_ADMIN_USERNAME:
-  PAS_ADMIN_PASSWORD:
-  PAS_ADMIN_ORG:
+  VARS_FILES:
+  # - Optional
+  # - Filepath to the vars yaml file
+  # - The path is relative to root of the task build,
+  #   so `vars` and `secrets` can be used.
+
+  CONFIG_FILE: base.yml
+  # - Required
+  # - Filepath to the base yaml file to interpolate from
+  # - The path is relative to root of the task build
 
   ENV_FILE: env.yml
   # - Required
   # - Filepath of the env config YAML
   # - The path is relative to root of the `env` input
+  SKIP_MISSING: true
+  # - Optional
+  # - Change to false to have strict interpolation
+  #   and fail if params are missing from vars
 
 run:
   path: bash
@@ -38,8 +48,29 @@ run:
     # add dependencies to platform automation image
     curl https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
     echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
-    apt-get update
-    apt-get install jq uaac -y
+    apt-get -y update
+    apt-get install jq ruby-full -y
+    gem install cf-uaac
+
+    # vars_files_args=("")
+    # for vf in ${VARS_FILES}
+    # do
+    #   vars_files_args+=("--vars-file ${vf}")
+    # done
+
+    if [ "$SKIP_MISSING" ]; then
+      export SKIP_MISSING="--skip-missing"
+    else
+      export SKIP_MISSING=""
+    fi
+
+    # ${vars_files_args[@] needs to be globbed to pass through properly
+    # shellcheck disable=SC2068
+    # om interpolate --config "config/$CONFIG_FILE" "$SKIP_MISSING" ${vars_files_args[@]} --path /properties_pks_api_hostname
+
+    GROUP_DISTINGUISHED_NAME=$(om interpolate --config "config/$CONFIG_FILE" "$SKIP_MISSING" --path /pks_admin_ldap_group_dn)
+
+    UAA_URL=$(om interpolate --config "config/$CONFIG_FILE" "$SKIP_MISSING" --path /properties_pks_api_hostname)
 
     PKS_GUID=$(om --env env/"${ENV_FILE}" curl --silent --path \
       "/api/v0/deployed/products" | \
@@ -52,27 +83,9 @@ run:
     echo "Connecting to PKS UAA server [$UAA_URL]..."
     # login to PKS UAA
     uaac target https://$UAA_URL:8443 --skip-ssl-validation
-    uaac token client get admin --secret $UAA_ADMIN_SECRET
+    uaac token client get admin --secret $ADMIN_CLIENT_SECRET
 
-    # uaac contexts > contexts.out
-    set +eu
-    CHK=$(uaac users | grep $PKS_ADMIN_USERNAME)
-    if [ -z "$CHK" ]; then
-      echo "Creating new PKS CLI administrator user per PK tile documentation https://docs.pivotal.io/runtimes/pks/1-0/manage-users.html#uaa-scopes"
-      uaac user add "$PKS_ADMIN_USERNAME" --emails "$PKS_ADMIN_USEREMAIL" -p "$PKS_ADMIN_PASSWORD"
-      echo "PKS CLI administrator user [$PKS_ADMIN_USERNAME] successfully created."
-    else
-      echo "user [$PKS_ADMIN_USERNAME] already exists"
-    fi
-
-    uaac member add pks.clusters.admin $PKS_ADMIN_USERNAME
-    uaac member add pks.clusters.admin admin
-    uaac member add uaa.admin $PKS_ADMIN_USERNAME
-    set -eu
-
-    echo "Next, download the PKS CLI from Pivotal Network and login to the PKS API to create a new K8s cluster [https://docs.pivotal.io/runtimes/pks/1-0/create-cluster.html]"
-    echo "Example: "
-    echo "   pks login -a $UAA_URL -u $PKS_ADMIN_USERNAME -p <pks-admin-password-provided>"
-
-
-# code_snippet add_pass_admin end
+    # set +eu
+    uaac group map --name pks.clusters.admin "$GROUP_DISTINGUISHED_NAME"
+    uaac group map --name pks.clusters.manage "$GROUP_DISTINGUISHED_NAME"
+    # set -eu
